import type { WeaponDefinition } from '../types/weapons';

export const WEAPONS: Record<string, WeaponDefinition> = {
  'baby-missile': {
    type: 'baby-missile',
    name: 'Baby Missile',
    category: 'projectile',
    explosionRadius: 15,
    damage: 20,
    price: 0,
    affectedByWind: true,
    affectedByGravity: true,
  },
  missile: {
    type: 'missile',
    name: 'Missile',
    category: 'projectile',
    explosionRadius: 25,
    damage: 35,
    price: 5000,
    affectedByWind: true,
    affectedByGravity: true,
  },
  mirv: {
    type: 'mirv',
    name: 'MIRV',
    category: 'cluster',
    explosionRadius: 20,
    damage: 25,
    price: 15000,
    clusterCount: 5,
    affectedByWind: true,
    affectedByGravity: true,
  },
  nuke: {
    type: 'nuke',
    name: 'Nuke',
    category: 'projectile',
    explosionRadius: 80,
    damage: 100,
    price: 50000,
    affectedByWind: false,
    affectedByGravity: true,
  },
  napalm: {
    type: 'napalm',
    name: 'Napalm',
    category: 'special',
    explosionRadius: 40,
    damage: 15,
    price: 12000,
    affectedByWind: true,
    affectedByGravity: true,
  },
  'holy-hand-grenade': {
    type: 'holy-hand-grenade',
    name: 'Holy Hand Grenade',
    category: 'projectile',
    explosionRadius: 60,
    damage: 80,
    price: 35000,
    affectedByWind: false,
    affectedByGravity: true,
  },
  'banana-bomb': {
    type: 'banana-bomb',
    name: 'Banana Bomb',
    category: 'cluster',
    explosionRadius: 30,
    damage: 40,
    price: 25000,
    clusterCount: 5,
    affectedByWind: true,
    affectedByGravity: true,
  },
  'smoke-tracer': {
    type: 'smoke-tracer',
    name: 'Smoke Tracer',
    category: 'projectile',
    explosionRadius: 0,
    damage: 0,
    price: 0,
    affectedByWind: true,
    affectedByGravity: true,
  },
  grenade: {
    type: 'grenade',
    name: 'Grenade',
    category: 'projectile',
    explosionRadius: 35,
    damage: 45,
    price: 8000,
    affectedByWind: true,
    affectedByGravity: true,
  },
  shotgun: {
    type: 'shotgun',
    name: 'Shotgun',
    category: 'beam',
    explosionRadius: 10,
    damage: 25,
    price: 6000,
    affectedByWind: false,
    affectedByGravity: false,
  },
  'fire-punch': {
    type: 'fire-punch',
    name: 'Fire Punch',
    category: 'special',
    explosionRadius: 5,
    damage: 30,
    price: 0,
    affectedByWind: false,
    affectedByGravity: false,
  },
  'baseball-bat': {
    type: 'baseball-bat',
    name: 'Baseball Bat',
    category: 'special',
    explosionRadius: 5,
    damage: 15,
    price: 0,
    affectedByWind: false,
    affectedByGravity: false,
  },
  roller: {
    type: 'roller',
    name: 'Roller',
    category: 'special',
    explosionRadius: 20,
    damage: 30,
    price: 4000,
    affectedByWind: false,
    affectedByGravity: false,
  },
  digger: {
    type: 'digger',
    name: 'Digger',
    category: 'terrain',
    explosionRadius: 15,
    damage: 20,
    price: 5000,
    affectedByWind: false,
    affectedByGravity: true,
  },
  'dirt-bomb': {
    type: 'dirt-bomb',
    name: 'Dirt Bomb',
    category: 'terrain',
    explosionRadius: 30,
    damage: 0,
    price: 3000,
    affectedByWind: true,
    affectedByGravity: true,
  },
  'air-strike': {
    type: 'air-strike',
    name: 'Air Strike',
    category: 'special',
    explosionRadius: 20,
    damage: 25,
    price: 15000,
    clusterCount: 5,
    affectedByWind: false,
    affectedByGravity: true,
  },
  'concrete-donkey': {
    type: 'concrete-donkey',
    name: 'Concrete Donkey',
    category: 'special',
    explosionRadius: 25,
    damage: 999,
    price: 100000,
    affectedByWind: false,
    affectedByGravity: true,
  },
  'guided-missile': {
    type: 'guided-missile',
    name: 'Guided Missile',
    category: 'special',
    explosionRadius: 30,
    damage: 50,
    price: 20000,
    affectedByWind: false,
    affectedByGravity: false,
  },
  armageddon: {
    type: 'armageddon',
    name: 'Armageddon',
    category: 'special',
    explosionRadius: 25,
    damage: 30,
    price: 80000,
    affectedByWind: false,
    affectedByGravity: true,
  },
} as const;
