import type { WeaponDefinition } from '../types/weapons';

export const WEAPONS: Record<string, WeaponDefinition> = {
  'baby-missile': {
    type: 'baby-missile',
    name: 'Baby Missile',
    category: 'projectile',
    explosionRadius: 15,
    damage: 20,
    price: 0,
    affectedByWind: true,
    affectedByGravity: true,
  },
  missile: {
    type: 'missile',
    name: 'Missile',
    category: 'projectile',
    explosionRadius: 25,
    damage: 35,
    price: 5000,
    affectedByWind: true,
    affectedByGravity: true,
  },
  mirv: {
    type: 'mirv',
    name: 'MIRV',
    category: 'cluster',
    explosionRadius: 20,
    damage: 25,
    price: 15000,
    clusterCount: 5,
    affectedByWind: true,
    affectedByGravity: true,
  },
  nuke: {
    type: 'nuke',
    name: 'Nuke',
    category: 'projectile',
    explosionRadius: 80,
    damage: 100,
    price: 50000,
    affectedByWind: false,
    affectedByGravity: true,
  },
  napalm: {
    type: 'napalm',
    name: 'Napalm',
    category: 'special',
    explosionRadius: 40,
    damage: 15,
    price: 12000,
    affectedByWind: true,
    affectedByGravity: true,
  },
  'holy-hand-grenade': {
    type: 'holy-hand-grenade',
    name: 'Holy Hand Grenade',
    category: 'projectile',
    explosionRadius: 60,
    damage: 80,
    price: 35000,
    affectedByWind: false,
    affectedByGravity: true,
  },
  'banana-bomb': {
    type: 'banana-bomb',
    name: 'Banana Bomb',
    category: 'cluster',
    explosionRadius: 30,
    damage: 40,
    price: 25000,
    clusterCount: 5,
    affectedByWind: true,
    affectedByGravity: true,
  },
} as const;
